sites:
  "rhe.jp":
    root: /srv/http/rhe.jp
    index: index.html
    default-type: text/plain
    dependency-map: ./dependency.yml
    prefixes:
      "/shoot":
        host: shootingstar.fm
        port: 80
      "/~":
        host: cashew
        port: 80
